# Generated by Django 4.0.6 on 2022-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', ''), ('S', 'Shirt'), ('SW', 'Sportwear'), ('OW', 'Outwear')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('', ''), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='', max_length=1),
        ),
    ]
