# Generated by Django 4.0.6 on 2022-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discaunt_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
