# Generated by Django 4.0.6 on 2022-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discaunt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is the test description', max_length=1000),
            preserve_default=False,
        ),
    ]
